apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint
  namespace: ci-mlperf-postprocess
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: aws-credential
      mountPath: /root/.aws
    - name: internal-pypi-secret
      mountPath: /root/.netrc
      readOnly: true
  params:
    - name: image
      description: The container image to use black in
      default: asia-northeast3-docker.pkg.dev/next-gen-infra/furiosa-ai/mlperf-postprocess:221102
  steps:
    - name: format
      env:
        - name: "PIP_EXTRA_INDEX_URL"
          value: "https://internal-pypi.furiosa.dev/simple"
      image: $(params.image)
      script: |
        #!/usr/bin/env bash
        set -e
        cd /workspace/source
        rustup component add rustfmt clippy
        make lint
      resources:
        requests:
          memory: 8Gi
          cpu: 4
        limits:
          memory: 8Gi
          cpu: 4
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: unittest
  namespace: ci-mlperf-postprocess
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: aws-credential
      mountPath: /root/.aws
    - name: internal-pypi-secret
      mountPath: /root/.netrc
      readOnly: true
  params:
    - name: image
      description: The container image to use black in
      default: asia-northeast3-docker.pkg.dev/next-gen-infra/furiosa-ai/mlperf-postprocess:221102
  steps:
    - name: unittest
      env:
        - name: "PIP_EXTRA_INDEX_URL"
          value: "https://internal-pypi.furiosa.dev/simple"
      image: $(params.image)
      script: |
        #!/usr/bin/env bash
        set -e
        cd /workspace/source
        make test
      resources:
        requests:
          memory: 32Gi
          cpu: 8
        limits:
          memory: 32Gi
          cpu: 8
